/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.g;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/getmoduleconfigurationparameters/
 */
public class GetModuleConfigurationParametersPayload extends Payload {

	/***
	 * Obtains the Module Configuration Parameters
	 * @param moduleType The module type to be activated
	 * @param moduleName The module name to be activated
	 */
	public GetModuleConfigurationParametersPayload(String moduleType, String moduleName) {
		super("GetModuleConfigurationParameters");
		put("moduleType", moduleType);
		put("moduleName", moduleName);
	}

}
