/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.g;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/getproject/
 */
public class GetProjectPayload extends Payload {

	/***
	 * Retrieve a specific Project
	 * @param projectid The project id to obtain
	 */
	public GetProjectPayload(int projectid) {
		super("GetProject");
		put("projectid", projectid);
	}

}
