/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.g;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/getservers/
 */
public class GetServersPayload extends Payload {

	/*
	 * Get servers.
	 */
	public GetServersPayload() {
		super("GetServers");
	}

	/***
	 * @param fetchStatus
	 * @return
	 */
	public GetServersPayload withFetchStatus(boolean fetchStatus) {
		put("fetchStatus", fetchStatus);

		return this;
	}

}
