/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.g;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/getstaffonline/
 */
public class GetStaffOnlinePayload extends Payload {

	/*
	 * Retrieve a list of currently logged in admin users.
	 */
	public GetStaffOnlinePayload() {
		super("GetStaffOnline");
	}

}
