/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.d;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/deleteticket/
 */
public class DeleteTicketPayload extends Payload {

	/*
	 * Deletes a ticket.
	 *
	 * @param ticketID The ticket to be deleted
	 */
	public DeleteTicketPayload(int ticketID) {
		super("DeleteTicket");
		put("ticketid", ticketID);
	}

}
