/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.d;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/domainrenew/
 */
public class DomainRenewPayload extends Payload {

	/*
	 * Sends the Renew command to the registrar for the domain
	 */
	public DomainRenewPayload() {
		super("DomainRenew");
	}

	public DomainRenewPayload withDomainid(int domainid) {
		put("domainid", domainid);

		return this;
	}

	public DomainRenewPayload withDomain(String domain) {
		put("domain", domain);

		return this;
	}

	public DomainRenewPayload withRegperiod(int regperiod) {
		put("regperiod", regperiod);

		return this;
	}

}
