/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.d;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/domainupdatelockingstatus/
 */
public class DomainUpdateLockingStatusPayload extends Payload {

	/***
	 * Sends the Update Lock command to the registrar for the domain
	 * @param domainID The id of the domain to update the locking status for
	 */
	public DomainUpdateLockingStatusPayload(int domainID) {
		super("DomainUpdateLockingStatus");
		put("domainid", domainID);
	}

	/***
	 * @param lockAtatus Should the domain lock be turned on
	 */
	public DomainUpdateLockingStatusPayload withLockStatus(boolean lockAtatus) {
		put("lockstatus", lockAtatus);

		return this;
	}

}
