INSERT INTO tbladmins
(id, uuid, roleid, username, password, passwordhash, authmodule, authdata, firstname, lastname, email, signature, notes, template, `language`, disabled, loginattempts, supportdepts, ticketnotifications, homewidgets, password_reset_key, password_reset_data, password_reset_expiry, hidden_widgets, widget_order, user_preferences, created_at, updated_at)
VALUES(1, '31b9b5ed-72b8-4734-9482-1bf756ea0031', 1, 'hoadq', '$2y$10$PC56.6bKexZEKXy2XOxQAOZ50ovb.3qmNIuVEAUq6xxy3HYJYtsiK', '$2y$10$bVujVDxM1nhQtJoDQDhbSO9UbNr.kKCTtd3CI/UNzoM.O6YQJHa9S', '', '', 'Hoa', 'Doan', 'hoadq@skynetidc.com', '', '', 'blend', 'english', 0, 0, ',1,2,', ',2,', 'getting_started:true,orders_overview:true,supporttickets_overview:true,my_notes:true,client_activity:true,open_invoices:true,activity_log:true|income_overview:true,system_overview:true,whmcs_news:true,sysinfo:true,admin_activity:true,todo_list:true,network_status:true,income_forecast:true|', '', '', NULL, ',BalanceWidget,', ',Overview,Automation,Activity,Billing,MarketConnect,Staff,ToDo,ClientActivity,NetworkStatus,Health,Support,BalanceWidget,', NULL, NULL, '2024-11-23 16:16:17.000');

INSERT INTO tblimage (name, code, `type`) VALUES
('Ubuntu 20.04', 'ubuntu', 'os'),
('Ubuntu 22.04', 'ubuntu', 'os'),
('Ubuntu 24.04', 'ubuntu', 'os'),
('Window Server 2019', 'window', 'os'),
('Window Server 2022', 'window', 'os');




INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(96, 59, 99, 6, 4, '2025-02-09', 'skynetidc.com', 'qrCode', 1, 25390.00, 25390.00, 'Monthly', '2025-04-09', '2025-04-09', '2025-03-12', NULL, 'Terminated', 'nguikern', '3aW78gbAzZpymK4rDPdQt5VtR4T1guQVFegtlmpevmOPpA==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 1, 1024, 0, 1048576, NULL, '2025-02-22 08:20:24.000', NULL, '2025-02-09 17:18:10.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(97, 59, 100, 6, 4, '2025-02-14', 'skynetidc123xy.online', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, '2025-03-12', NULL, 'Cancelled', 'ueukrblt', 'quWrl4tVyX3+An+uCPBoCJvswSHApoVg4X0nOJHpV9rQtQ==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 82, 1024, 30, 1048576, NULL, '2025-02-22 08:20:24.000', NULL, '2025-02-14 16:05:00.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(98, 59, 101, 6, 4, '2025-02-14', 'skynetidc123.online', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, '2025-03-12', NULL, 'Terminated', 'dcpdpgpz', '8TfztKnxNQ0k06w+HjRHdl6JMyqLEq45kJHhTDMlxj77Jg==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 0, 1024, 0, 1048576, NULL, '2025-02-22 08:20:24.000', NULL, '2025-02-14 16:20:41.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(99, 59, 102, 6, 4, '2025-02-15', 'skynetidc.vn', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, '2025-02-16', NULL, 'Terminated', 'veughxsn', '391HtuFltJMt9ef/N5n19CATOXWP+HQwyBh3pVEiko6qhg==', '', '', NULL, 0, 0, 'Khong Su Dung', 0, NULL, '', '', '', '', 0, 1024, 0, 1048576, NULL, '2025-02-22 08:20:24.000', NULL, '2025-02-15 16:26:45.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(100, 59, 103, 6, 4, '2025-02-15', 'skynetidc.com.vn', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, '2025-03-12', NULL, 'Terminated', 'kkdgjyna', 'ikm3nEIRtDdv3DBROp1NPaboC2a2DfwDTzh1FXVZBBLrgA==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 2, 1024, 8, 1048576, NULL, '2025-02-27 15:40:14.000', NULL, '2025-02-15 17:47:06.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(101, 59, 107, 6, 4, '2025-02-17', 'quanghoa.info', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, '2025-02-27', NULL, 'Terminated', 'noinfclz', 'tapf8JHhrHfj1RtFSs8itZPDIYGOmmhemZglRbYiOV7LvA==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 82, 1024, 143, 1048576, NULL, '2025-02-27 15:40:14.000', NULL, '2025-02-17 05:38:02.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(102, 59, 108, 6, 4, '2025-02-27', 'quanghoa.org', 'qrCode', 1, 44400000.00, 0.00, 'One Time', NULL, NULL, '2025-03-12', NULL, 'Terminated', 'eabltond', '2vWNXvyAeq24x+7n2qSkchlWiqTlsqDSxL+2iu5ZyptcvQ==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 0, 1024, 0, 1048576, NULL, '2025-02-27 15:40:14.000', NULL, NULL);
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(103, 59, 109, 6, 4, '2025-02-27', 'quanghoa.net', 'qrCode', 1, 2650000.00, 0.00, 'One Time', NULL, NULL, '2025-03-12', NULL, 'Terminated', 'qcqjvemm', 'ZejWVBweB+s2n+irTGqHMQaLU4c1oJ6gGXeW9yEG39WZdQ==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 0, 0, 0, 0, NULL, NULL, NULL, '2025-02-27 16:18:47.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(105, 59, 111, 6, 4, '2025-02-27', 'quanghoa.io', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, NULL, NULL, 'Active', 'cfrcajhg', 'aKXeP0TICC2ou6Znn9BNI8wGj+cb5rWJUKD1a7YszwUQ2g==', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 0, 0, 0, 0, NULL, NULL, NULL, NULL);
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(106, 59, 0, 6, 4, '2025-03-10', 'skynetidc.vn', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, NULL, NULL, 'Active', 'skynetidc', '6+NLdLfeWhvs2+y0DMnRijBYhWSsuHbeuPjIK/RW2+nI1g==', 'Auto-created service from Server Sync Tool', '', NULL, 0, 0, '', 0, NULL, '13.212.181.0', '', '', '', 1, 0, 29, 0, NULL, '2025-03-17 02:20:05.000', '2025-03-10 17:55:17.000', '2025-03-10 17:55:17.000');
INSERT INTO portal.tblhosting
(id, userid, orderid, packageid, server, regdate, `domain`, paymentmethod, qty, firstpaymentamount, amount, billingcycle, nextduedate, nextinvoicedate, termination_date, completed_date, domainstatus, username, password, notes, subscriptionid, recommendation_source_product_id, promoid, promocount, suspendreason, overideautosuspend, overidesuspenduntil, dedicatedip, assignedips, ns1, ns2, diskusage, disklimit, bwusage, bwlimit, upsell_from_products, lastupdate, created_at, updated_at)
VALUES(107, 59, 112, 6, 4, '2025-03-10', 'skynetidc.site', 'qrCode', 1, 0.00, 0.00, 'Free Account', NULL, NULL, NULL, NULL, 'Active', 'npmdrbzd', 'wgxU6LEOseRXFrx4ybPbLVpyroSYaDBCi3dn8DiJxntN', '', '', NULL, 0, 0, '', 0, NULL, '', '', '', '', 81, 1024, 0, 0, NULL, '2025-03-17 02:20:05.000', NULL, NULL);
