/**
 * Generated by ramidzkh's awesome generator thingy
 */
package com.skynetidc.client.payload.f;

import com.skynetidc.client.payload.Payload;

/***
 * This class and its methods directly relate to the API documentation. API documentation
 * can be found at the￼ following URL: ￼*
 * https://developers.whmcs.com/api-reference/fraudorder/
 */
public class FraudOrderPayload extends Payload {

	/***
	 * Marks an order as fraudulent.
	 * @param orderid The Order ID to set as fraud
	 */
	public FraudOrderPayload(int orderid) {
		super("FraudOrder");
		put("orderid", orderid);
	}

	/***
	 * @param cancelsub Pass as true to cancel any PayPal Subscription(s) associated with
	 * the products & services that belong to the given order.
	 */
	public FraudOrderPayload withCancelsub(boolean cancelsub) {
		put("cancelsub", cancelsub);

		return this;
	}

}
