const { GoogleSpreadsheet } = require('google-spreadsheet') ;
const { JWT } = require('google-auth-library') ;
const config = require('../config');

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: config.googleService.accountEmail,
    key: config.googleService.privateKey,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    addRow: async function (sheetId, sheetIndex, rowData) {
        const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);
        await doc.loadInfo(); // loads document properties and worksheets
        const sheet = doc.sheetsByIndex[sheetIndex]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
        await sheet.addRow(rowData);
    }
}
