server:
  port: 8080

spring:
  thymeleaf:
    mode: HTML
  messages:
    basename: messages/messages

logging:
  level:
    org:
      springframework: INFO
      web: DEBUG
      context:
        annotation: TRACE
